---
- name: Install tomcat10 and apache2
  hosts: all
  tasks:
    - name: Install apache2
      include_tasks: install.yml
    - name: Install tomcat
      apt:
        name: tomcat10
        state: present
        update_cache: yes
...
