---
- name: Install GIT based on OS flavor
  hosts: all
  become: yes

  tasks:
    - name: Install GIT on Ubuntu servers using apt
      apt:
        name: git
        state: present
        update_cache: yes
      when: ansible_facts['distribution'] == "Ubuntu"

    - name: Install GIT on RedHat servers using yum
      yum:
        name: git
        state: present
      when: ansible_facts['distribution'] == "RedHat"
